# Generated by Django 4.2.5 on 2023-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('emailAlt', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
